; jupiter runtime header for version 0.0.6

declare void @ju_init ()
declare void @ju_destroy ()
declare void @juGC_root (i8**)
declare void @juGC_unroot (i32)
declare void @juGC_store (i8**, i8*)
declare i32 @ju_to_int (i8*)
declare i1  @ju_to_bool (i8*)
declare i8* @ju_from_int (i32)
declare i8* @ju_from_bool (i1)
declare i1  @ju_is_int (i8*)
declare i8* @ju_make_buf (i32, i32, i32, ...)
declare i8* @ju_make_str (i8*, i32)
declare i8* @ju_make_real (double)
declare i8* @ju_get (i8*, i32)
declare i8* @ju_safe_get (i8*, i8*, i32, i32)
declare i32 @ju_get_tag (i8*)
